const std = @import("std");

pub const ValueIndex = enum(u32) {
    zero,
    true = 1,
    false = 2,
    type_float = 3,
    type_double = 5,
    type_short = 7,
    type_long = 9,
    type_long_long = 11,
    type_unrestricted_float = 13,
    type_unrestricted_double = 15,
    type_unsigned_short = 17,
    type_unsigned_long = 19,
    type_unsigned_long_long = 21,
    type_boolean = 23,
    type_byte = 25,
    type_octet = 27,
    type_bigint = 29,
    type_ByteString = 31,
    type_DOMString = 33,
    type_USVString = 35,
    type_ArrayBuffer = 37,
    type_SharedArrayBuffer = 39,
    type_DataView = 41,
    type_Int8Array = 43,
    type_Int16Array = 45,
    type_Int32Array = 47,
    type_Uint8Array = 49,
    type_Uint16Array = 51,
    type_Uint32Array = 53,
    type_Uint8ClampedArray = 55,
    type_BigInt64Array = 57,
    type_BigUint64Array = 59,
    type_Float32Array = 61,
    type_Float64Array = 63,

    _,
};

pub const Value = union(enum(u8)) {
    zero,
    string: StringIndex,
    identifier: IdentifierIndex,
    true,
    false,
    type: TypeIndex,
    integer: IntegerIndex,

    pub const Tag = std.meta.Tag(@This());
};

pub const StringIndex = enum(u32) {
    _,
};

pub const IdentifierIndex = enum(u32) {
    _,
};

pub const TypeIndex = enum(u32) {
    float = 3,
    double = 5,
    short = 7,
    long = 9,
    long_long = 11,
    unrestricted_float = 13,
    unrestricted_double = 15,
    unsigned_short = 17,
    unsigned_long = 19,
    unsigned_long_long = 21,
    boolean = 23,
    byte = 25,
    octet = 27,
    bigint = 29,
    ByteString = 31,
    DOMString = 33,
    USVString = 35,
    ArrayBuffer = 37,
    SharedArrayBuffer = 39,
    DataView = 41,
    Int8Array = 43,
    Int16Array = 45,
    Int32Array = 47,
    Uint8Array = 49,
    Uint16Array = 51,
    Uint32Array = 53,
    Uint8ClampedArray = 55,
    BigInt64Array = 57,
    BigUint64Array = 59,
    Float32Array = 61,
    Float64Array = 63,

    _,
};

pub const Type = enum(u8) {
    float,
    double,
    short,
    long,
    long_long,
    unrestricted_float,
    unrestricted_double,
    unsigned_short,
    unsigned_long,
    unsigned_long_long,
    boolean,
    byte,
    octet,
    bigint,
    named,
    enumeration,
    ByteString,
    DOMString,
    USVString,
    ArrayBuffer,
    SharedArrayBuffer,
    DataView,
    Int8Array,
    Int16Array,
    Int32Array,
    Uint8Array,
    Uint16Array,
    Uint32Array,
    Uint8ClampedArray,
    BigInt64Array,
    BigUint64Array,
    Float32Array,
    Float64Array,
};

pub const IntegerIndex = enum(u32) {
    _,
};
